server:
  port: 8080
keycloak:
  enabled: true
  realm: springBoot
  auth-server-url: http://192.168.9.160:8080/auth
  ssl-required: external
  resource: boot-test
  enableBasicAuth: true
  credentials:
    secret: bccdf485-7994-4157-aa0f-d775311636fa
  use-resource-role-mappings: true
#  bearer-only: true //이거 하면 loginpage로 안가짐
#  public-client: true //이거하면 login 이후 whitelabel 403 페이지 뜸
  principal-attribute: preferred_username

#  token-store: cookie



